### ISSUE TITLE
Change SPM library to dynamic instead of static

### ISSUE THREAD

**Issue by marekpridal** [kishikawakatsumi/KeychainAccess#472]
Hi, since Xcode 11.4b1 I'm unable to use KeychainAccess imported using SwiftPM in main app target and Today widget target at the same time. It's because SwiftPM by default imports dependencies as static library. Is there a chance to update Package.swift manifest to produce dynamic framework? I found out it [should be pretty simple](https://stackoverflow.com/questions/58090099/swift-package-manager-dynamic-library) and I can send PR if your are open to it.

**Comment by jonasmunk** [comment]
I have the same issue in the final Xcode 11.4. Cannot link in both main app and share extension.

**Comment by rval** [comment]
Yep, running into this same problem too. I suspect more and more of us will now that Xcode 11.4 is out of beta.

**Comment by Danappelxx** [comment]
I used @GZaccaroni's fork (which just changes the product to a dynamic library) and it built fine. However, I got an error pushing to iTunes Connect, saying extensions aren't allowed to embed frameworks.

I'm sure there's a better solution, but I ended up just adding the file `Keychain.swift` to my project.

**Comment by GZaccaroni** [comment]
@Danappelxx i also had to manually edit xcproj file, there _must_ be a better solution.

**Comment by kishikawakatsumi** [comment]
Hi all, this is Xcode 11.4's new diagnostics system's bug. Changing static library to dynamic library doesn't help as @Danappelxx mentioned.

Also, Since the main app and extensions are separate targets and run as separate processes, it is perfectly correct to statically link the library to each target.

Thus, you can work around this bug in the following way:

https://forums.swift.org/t/adding-a-package-to-two-targets-in-one-projects-results-in-an-error/35007/2

To add `DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC=YES` to your Xcode project build settings.

1. Select the blue project file in the target pane.
2. Click the "+" button and select "Add User-Defined Setting"
3. Set key `DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC` and value `YES`

<img width="820" alt="Screen Shot 2020-04-09 at 10 33 36" src="https://user-images.githubusercontent.com/40610/78848745-9fc85c00-7a4d-11ea-8fc0-358c5f23eb31.png">

**Comment by kishikawakatsumi** [comment]
This issue was fixed by Xcode 11.4.1.
> Swift Packages
> Resolved Issues
> Fixed an issue where an error like “Swift package product A is linked as a static library by B and C. This will result in duplication of library code.” was incorrectly emitted if an app and an embedded app extension or helper tool statically linked the same package product. If you previously set the DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC build setting to work around this issue, you can delete this setting now. (59310009, 61227255)

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_1_release_notes

**Comment by pavm035** [comment]
I think this will be still problem if we link this SPM product into as below

A-Framework -> KeychainAccess(SPM)
App ->  KeychainAccess(SPM)
App -> A-Framework

**Comment by OlegEremenko991** [comment]
> This issue was fixed by Xcode 11.4.1. No longer needed `DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC=YES`
> 
> > Swift Packages
> > Resolved Issues
> > Fixed an issue where an error like “Swift package product A is linked as a static library by B and C. This will result in duplication of library code.” was incorrectly emitted if an app and an embedded app extension or helper tool statically linked the same package product. If you previously set the DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC build setting to work around this issue, you can delete this setting now. (59310009, 61227255)
> 
> https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_1_release_notes

The issue is back with Xcode 13, but this time DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC does not work.
I have to manually remove 'Frameworks' folder from app extension after archiving.
